---
- name: Creating files / directory
  hosts: all
  become: true
  gather_facts: no

  tasks:

    - name: Create a file
      file:
        path: /home/ec2-user/testfile
        state: touch
        mode: 0755
        owner: ansadmin
