---
- name: Installing packages
  hosts: all 
  gather_facts: no
  become: true
  tasks:

    - name: Installing git packages
      yum:
        name: git
        state: installed

    - name: Installing httpd packages
      yum:
        name: httpd
        state: installed

    - name: Starting the httpd service
      service:
        name: httpd
        state: started

    - name: copy th file
      copy:
        src: /home/ansadmin/playbook/index.html
        dest: /var/www/html