---
- name: Install jenkins
  hosts: all 
  become: true
  gather_facts: no

  tasks:
    - name: Install java
      yum:
        name: {{ item }}
        state: installed
      with_items:
        - java-1.8*
        - wget

    - name: downloading jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: adding jenkins key
      rpm_key:
        state: present
        key:  https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: epel release
      yum:
        name: epel-release
        state: installed

    - name: Install jenkins
      yum:
        name: jenkins
        state: installed

    - name: start jenkins server
      service:
        name: jenkins
        state: started
        enabled: yes
